# Generated by Django 5.1.3 on 2024-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_photos/"
            ),
        ),
    ]
