# Generated by Django 5.1.3 on 2024-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0002_equipment_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="campus_photos/"),
        ),
    ]
