# Generated by Django 5.1.3 on 2024-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_campus_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
    ]
