# Generated by Django 5.1.3 on 2024-12-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0004_room_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="Default Room", max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Площадь"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classrooms.campus",
                verbose_name="Корпус",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classrooms.department",
                verbose_name="Факультет",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.IntegerField(verbose_name="Этаж"),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=10, verbose_name="Номер аудитории"),
        ),
        migrations.AlterField(
            model_name="room",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="rooms/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classrooms.roomtype",
                verbose_name="Тип аудитории",
            ),
        ),
    ]
